---
- name: Установить и настроить Lighthouse
  block:
    - name: Установить зависимости для dnf
      ansible.builtin.dnf:
        name:
          - nodejs
          - npm
        state: present
      when: ansible_facts.pkg_mgr == 'dnf'

    - name: Установить зависимости для apt
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present
      when: ansible_facts.pkg_mgr == 'apt'

    - name: Установить переменную lighthouse_version
      ansible.builtin.set_fact:
        v_version: "{{ lighthouse_version }}"

    - name: Создать директорию для установки Lighthouse
      ansible.builtin.file:
        path: "{{ lighthouse_install_dir }}"
        state: directory
        mode: "0755"

    - name: Установить Lighthouse глобально
      ansible.builtin.shell: |
        npm install -g lighthouse@{{ v_version }}
      args:
        warn: false
      register: npm_install_result
      changed_when: npm_install_result.rc != 0
      environment:
        NODE_ENV: "production"

    - name: Проверить установку Lighthouse
      ansible.builtin.command: lighthouse --version
      register: lighthouse_version_check
      changed_when: false

    - name: Скопировать файл конфигурации Lighthouse
      ansible.builtin.template:
        src: "{{ lighthouse_config_template }}"
        dest: "{{ lighthouse_install_dir }}/lighthouse-config.json"
        mode: "0644"

    - name: Запустить Lighthouse с конфигурацией
      ansible.builtin.command: lighthouse --config={{ lighthouse_install_dir }}/lighthouse-config.json
      register: lighthouse_run
      changed_when: lighthouse_run.rc != 0
